package com.mdstudio.closedtesttracker

private fun proValues(
    tr: String, fr: String, es: String, zh: String, hi: String, ru: String,
    ar: String, de: String, ja: String, pt: String, id: String
) = listOf(tr, "", fr, es, zh, hi, ru, ar, de, ja, pt, id)

private val advancedProStrings = mapOf(
    "Your complete professional testing toolkit." to proValues("Profesyonel test sürecin için tüm araçlar hazır.", "Tous vos outils professionnels de test sont prêts.", "Todas tus herramientas profesionales de prueba están listas.", "完整的专业测试工具已准备就绪。", "आपका पूरा पेशेवर टेस्ट टूलकिट तैयार है।", "Полный набор профессиональных инструментов для тестирования.", "مجموعة أدوات الاختبار الاحترافية الكاملة جاهزة.", "Dein vollständiges professionelles Testpaket.", "プロ向けテストツールがすべて利用できます。", "Seu kit profissional completo de testes.", "Perangkat pengujian profesional lengkap Anda."),
    "Unlock the toolkit and remove ads with one payment." to proValues("Tek ödeme ile araçları aç ve reklamları kaldır.", "Débloquez les outils et supprimez les publicités avec un paiement unique.", "Desbloquea las herramientas y elimina anuncios con un solo pago.", "一次付费即可解锁工具并移除广告。", "एक भुगतान में टूल अनलॉक करें और विज्ञापन हटाएँ।", "Откройте инструменты и уберите рекламу одной покупкой.", "افتح الأدوات وأزل الإعلانات بدفعة واحدة.", "Werkzeuge freischalten und Werbung mit einer Zahlung entfernen.", "一度の支払いでツールを解放し、広告を削除します。", "Libere as ferramentas e remova anúncios com um pagamento.", "Buka alat dan hapus iklan dengan satu pembayaran."),
    "Unlock Pro" to proValues("Pro'yu aç", "Débloquer Pro", "Desbloquear Pro", "解锁 Pro", "Pro अनलॉक करें", "Открыть Pro", "فتح Pro", "Pro freischalten", "Proを解放", "Liberar Pro", "Buka Pro"),
    "One-time purchase with no subscription." to proValues("Tek seferlik satın alma; abonelik yok.", "Achat unique, sans abonnement.", "Compra única, sin suscripción.", "一次购买，无需订阅。", "एकमुश्त खरीद, कोई सदस्यता नहीं।", "Разовая покупка, без подписки.", "شراء لمرة واحدة، بدون اشتراك.", "Einmalkauf ohne Abo.", "買い切りで、定期購入はありません。", "Compra única, sem assinatura.", "Pembelian sekali, tanpa langganan."),
    "Closed testing roadmap" to proValues("Kapalı test yol haritası", "Feuille de route du test fermé", "Ruta de prueba cerrada", "封闭测试路线图", "क्लोज़्ड टेस्ट रोडमैप", "План закрытого тестирования", "خارطة طريق الاختبار المغلق", "Fahrplan für geschlossene Tests", "クローズドテストの手順", "Roteiro de teste fechado", "Peta jalan pengujian tertutup"),
    "A practical checklist for independent developers" to proValues("Bireysel geliştiriciler için uygulanabilir kontrol listesi", "Une liste pratique pour les développeurs indépendants", "Una lista práctica para desarrolladores independientes", "面向独立开发者的实用清单", "स्वतंत्र डेवलपर के लिए व्यावहारिक चेकलिस्ट", "Практический список для независимых разработчиков", "قائمة عملية للمطورين المستقلين", "Praktische Checkliste für unabhängige Entwickler", "個人開発者向けの実用チェックリスト", "Checklist prático para desenvolvedores independentes", "Daftar praktis untuk pengembang independen"),
    "Aim for 20 testers" to proValues("20 testçi hedefle", "Visez 20 testeurs", "Busca 20 testers", "以 20 名测试者为目标", "20 टेस्टर का लक्ष्य रखें", "Найдите около 20 тестировщиков", "استهدف 20 مختبرًا", "20 Tester anstreben", "20人のテスターを目標にする", "Busque 20 testadores", "Targetkan 20 penguji"),
    "Recruit about 20 real testers so you have a buffer if someone leaves. Always confirm the current requirement in Play Console." to proValues("Ayrılmaları hesaba katmak için yaklaşık 20 gerçek testçi bul. Güncel gereksinimi her zaman Play Console'dan doğrula.", "Recrutez environ 20 vrais testeurs pour prévoir les départs. Vérifiez toujours l'exigence actuelle dans Play Console.", "Recluta unos 20 testers reales para cubrir posibles bajas. Confirma siempre el requisito actual en Play Console.", "招募约 20 名真实测试者，以应对人员退出。请始终在 Play Console 中确认当前要求。", "किसी के छोड़ने की स्थिति के लिए लगभग 20 वास्तविक टेस्टर जोड़ें। मौजूदा आवश्यकता Play Console में जाँचें।", "Привлеките около 20 реальных тестировщиков с запасом на случай ухода. Проверяйте актуальные требования в Play Console.", "استعن بنحو 20 مختبرًا حقيقيًا كاحتياط عند انسحاب أحدهم. تحقق دائمًا من المتطلبات الحالية في Play Console.", "Gewinne etwa 20 echte Tester als Reserve. Prüfe die aktuelle Vorgabe immer in der Play Console.", "離脱に備えて約20人の実テスターを確保し、最新要件はPlay Consoleで確認してください。", "Recrute cerca de 20 testadores reais como margem para desistências. Confirme o requisito atual no Play Console.", "Rekrut sekitar 20 penguji nyata sebagai cadangan. Selalu periksa persyaratan terbaru di Play Console."),
    "Ask for real daily usage" to proValues("Her gün gerçek kullanım iste", "Demandez une utilisation réelle quotidienne", "Pide uso diario real", "要求每天真实使用", "रोज़ वास्तविक उपयोग के लिए कहें", "Просите о реальном ежедневном использовании", "اطلب استخدامًا يوميًا حقيقيًا", "Um echte tägliche Nutzung bitten", "毎日の実利用を依頼する", "Peça uso diário real", "Minta penggunaan nyata setiap hari"),
    "Do not ask testers to only open and close the app. Ask them to use key flows for at least 2 minutes each day and leave brief feedback." to proValues("Testçiler uygulamayı yalnızca açıp kapatmasın. Her gün en az 2 dakika ana akışları denesin ve kısa geri bildirim bıraksın.", "Ne demandez pas seulement d'ouvrir l'application. Demandez au moins 2 minutes d'utilisation quotidienne des fonctions principales et un bref retour.", "No pidas solo abrir y cerrar la app. Solicita al menos 2 minutos diarios usando funciones clave y comentarios breves.", "不要只让测试者打开后关闭应用。请他们每天至少使用核心流程 2 分钟并提供简短反馈。", "टेस्टर से केवल ऐप खोलने-बंद करने को न कहें। रोज़ कम से कम 2 मिनट मुख्य फ़्लो उपयोग करने और संक्षिप्त फ़ीडबैक देने को कहें।", "Не просите просто открыть и закрыть приложение. Пусть тестировщики ежедневно не менее 2 минут используют основные функции и оставляют краткий отзыв.", "لا تطلب من المختبرين فتح التطبيق وإغلاقه فقط. اطلب استخدام الوظائف الأساسية لدقيقتين يوميًا على الأقل وترك ملاحظة قصيرة.", "Tester sollen die App nicht nur öffnen und schließen. Bitte sie, täglich mindestens 2 Minuten wichtige Abläufe zu nutzen und kurz Feedback zu geben.", "起動して閉じるだけでなく、毎日2分以上主要機能を使い、短いフィードバックを残してもらいます。", "Não peça apenas para abrir e fechar o app. Solicite ao menos 2 minutos diários nos fluxos principais e feedback breve.", "Jangan minta penguji hanya membuka dan menutup aplikasi. Minta mereka memakai alur utama minimal 2 menit setiap hari dan memberi umpan balik singkat."),
    "Track all 14 days" to proValues("14 günü kesintisiz takip et", "Suivez les 14 jours", "Controla los 14 días", "跟踪完整 14 天", "पूरे 14 दिन ट्रैक करें", "Отслеживайте все 14 дней", "تابع الأيام الأربعة عشر", "Alle 14 Tage verfolgen", "14日間すべて追跡", "Acompanhe os 14 dias", "Lacak seluruh 14 hari"),
    "Check participation, daily usage and issues regularly. Send a polite reminder to missing testers and keep backup testers ready." to proValues("Katılımı, günlük kullanımı ve sorunları düzenli kontrol et. Eksik testçilere nazikçe hatırlat ve yedek testçi hazır tut.", "Vérifiez régulièrement la participation, l'utilisation et les problèmes. Rappelez poliment les absents et gardez des testeurs de secours.", "Revisa participación, uso y problemas. Recuerda amablemente a quienes falten y mantén testers de reserva.", "定期检查参与、每日使用和问题。礼貌提醒缺席者，并准备候补测试者。", "भागीदारी, दैनिक उपयोग और समस्याएँ नियमित जाँचें। अनुपस्थित टेस्टर को विनम्र रिमाइंडर भेजें और बैकअप रखें।", "Регулярно проверяйте участие, использование и проблемы. Вежливо напоминайте отсутствующим и держите резерв.", "تحقق بانتظام من المشاركة والاستخدام والمشكلات. ذكّر المتغيبين بلطف واحتفظ بمختبرين احتياطيين.", "Prüfe Teilnahme, Nutzung und Probleme regelmäßig. Erinnere fehlende Tester höflich und halte Ersatz bereit.", "参加状況、毎日の利用、問題を確認し、不足している人に丁寧に通知して予備も確保します。", "Verifique participação, uso e problemas. Lembre educadamente os ausentes e mantenha reservas.", "Periksa partisipasi, penggunaan, dan masalah secara rutin. Ingatkan penguji yang absen dengan sopan dan siapkan cadangan."),
    "Review permissions and declarations" to proValues("İzinleri ve beyanları kontrol et", "Vérifiez les autorisations et déclarations", "Revisa permisos y declaraciones", "检查权限和声明", "अनुमतियाँ और घोषणाएँ जाँचें", "Проверьте разрешения и декларации", "راجع الأذونات والإقرارات", "Berechtigungen und Angaben prüfen", "権限と申告を確認", "Revise permissões e declarações", "Tinjau izin dan deklarasi"),
    "Use only necessary Android permissions. Match Data safety, privacy, ads and payment declarations with the app's actual behavior." to proValues("Yalnızca gerekli Android izinlerini kullan. Veri güvenliği, gizlilik, reklam ve ödeme beyanlarını uygulamanın gerçek davranışıyla eşleştir.", "Utilisez uniquement les autorisations nécessaires. Faites correspondre sécurité des données, confidentialité, publicités et paiements au comportement réel.", "Usa solo permisos necesarios. Haz coincidir Seguridad de datos, privacidad, anuncios y pagos con el comportamiento real.", "仅使用必要的 Android 权限。确保数据安全、隐私、广告和付款声明与应用实际行为一致。", "केवल आवश्यक Android अनुमतियाँ लें। डेटा सुरक्षा, गोपनीयता, विज्ञापन और भुगतान घोषणाएँ ऐप के व्यवहार से मेल खाएँ।", "Используйте только необходимые разрешения. Декларации о данных, конфиденциальности, рекламе и оплате должны соответствовать реальному поведению.", "استخدم أذونات Android الضرورية فقط. طابق إقرارات أمان البيانات والخصوصية والإعلانات والدفع مع السلوك الفعلي.", "Nutze nur nötige Android-Berechtigungen. Angaben zu Datensicherheit, Datenschutz, Werbung und Zahlung müssen dem Verhalten entsprechen.", "必要な権限だけを使い、データセーフティ、プライバシー、広告、支払いの申告を実際の動作と一致させます。", "Use apenas permissões necessárias. Alinhe Segurança de dados, privacidade, anúncios e pagamentos ao comportamento real.", "Gunakan hanya izin Android yang diperlukan. Samakan deklarasi keamanan data, privasi, iklan, dan pembayaran dengan perilaku aplikasi."),
    "Avoid common mistakes" to proValues("Yaygın hatalardan kaçın", "Évitez les erreurs courantes", "Evita errores comunes", "避免常见错误", "आम गलतियों से बचें", "Избегайте частых ошибок", "تجنب الأخطاء الشائعة", "Häufige Fehler vermeiden", "よくあるミスを避ける", "Evite erros comuns", "Hindari kesalahan umum"),
    "Avoid fake or install-only testers. Do not go to production without recording crashes, ANRs, device model, Android version and reproduction steps." to proValues("Sahte veya yalnızca kurulum yapan testçiler kullanma. Çökme, ANR, cihaz modeli, Android sürümü ve tekrar adımlarını kaydetmeden üretime geçme.", "Évitez les faux testeurs ou ceux qui installent seulement. Ne publiez pas sans noter plantages, ANR, modèle, version Android et étapes de reproduction.", "Evita testers falsos o de solo instalación. No pases a producción sin registrar fallos, ANR, dispositivo, versión Android y pasos.", "避免虚假或只安装应用的测试者。记录崩溃、ANR、设备型号、Android 版本和复现步骤后再发布。", "नकली या केवल इंस्टॉल करने वाले टेस्टर से बचें। क्रैश, ANR, डिवाइस मॉडल, Android संस्करण और चरण दर्ज किए बिना प्रोडक्शन में न जाएँ।", "Избегайте фиктивных тестировщиков. Не выходите в продакшен без записи сбоев, ANR, модели, версии Android и шагов воспроизведения.", "تجنب المختبرين الوهميين أو من يثبتون فقط. لا تنتقل للإنتاج دون تسجيل الأعطال وANR وطراز الجهاز وإصدار Android وخطوات التكرار.", "Vermeide unechte oder reine Installationstester. Gehe nicht ohne Daten zu Abstürzen, ANRs, Gerät, Android-Version und Reproduktion in Produktion.", "偽のテスターやインストールだけの人を避け、クラッシュ、ANR、端末、Androidバージョン、再現手順を記録してから公開します。", "Evite testadores falsos ou que só instalam. Não publique sem registrar falhas, ANRs, modelo, versão Android e passos.", "Hindari penguji palsu atau hanya memasang. Jangan ke produksi tanpa mencatat crash, ANR, model, versi Android, dan langkah reproduksi."),
    "Reddit testing communities" to proValues("Reddit test toplulukları", "Communautés de test Reddit", "Comunidades de prueba en Reddit", "Reddit 测试社区", "Reddit टेस्ट समुदाय", "Сообщества тестировщиков Reddit", "مجتمعات الاختبار على Reddit", "Reddit-Testcommunities", "Redditテストコミュニティ", "Comunidades de teste no Reddit", "Komunitas pengujian Reddit"),
    "Read each community's rules and post an honest, relevant testing request. Avoid posting the same message everywhere at once." to proValues("Her topluluğun kurallarını oku ve dürüst, ilgili bir test talebi paylaş. Aynı gönderiyi her yere aynı anda gönderme.", "Lisez les règles de chaque communauté et publiez une demande honnête et pertinente. Évitez le même message partout à la fois.", "Lee las reglas y publica una solicitud honesta y relevante. Evita publicar el mismo mensaje en todas a la vez.", "阅读各社区规则并发布真实相关的测试请求。避免同时向所有社区发送相同内容。", "हर समुदाय के नियम पढ़ें और ईमानदार, प्रासंगिक अनुरोध पोस्ट करें। एक ही संदेश हर जगह एक साथ न डालें।", "Читайте правила каждого сообщества и публикуйте честный запрос. Не размещайте одно сообщение везде одновременно.", "اقرأ قواعد كل مجتمع وانشر طلب اختبار صادقًا وملائمًا. تجنب نشر الرسالة نفسها في كل مكان دفعة واحدة.", "Lies die Regeln jeder Community und poste eine ehrliche, passende Anfrage. Veröffentliche nicht überall gleichzeitig denselben Text.", "各コミュニティのルールを読み、正直で関連性のある依頼を投稿します。同じ投稿を一斉送信しないでください。", "Leia as regras e publique um pedido honesto e relevante. Evite postar a mesma mensagem em todos ao mesmo tempo.", "Baca aturan tiap komunitas dan kirim permintaan yang jujur dan relevan. Hindari memposting pesan sama di semua tempat sekaligus."),
    "Use placeholders to insert testing links automatically." to proValues("Test bağlantılarını otomatik yerleştirmek için değişkenleri kullan.", "Utilisez les variables pour insérer automatiquement les liens.", "Usa variables para insertar enlaces automáticamente.", "使用占位符自动插入测试链接。", "टेस्ट लिंक अपने आप जोड़ने के लिए प्लेसहोल्डर उपयोग करें।", "Используйте переменные для автоматической вставки ссылок.", "استخدم المتغيرات لإدراج روابط الاختبار تلقائيًا.", "Nutze Platzhalter zum automatischen Einfügen von Links.", "プレースホルダーでテストリンクを自動挿入します。", "Use variáveis para inserir links automaticamente.", "Gunakan placeholder untuk memasukkan tautan otomatis."),
    "Preview" to proValues("Önizleme", "Aperçu", "Vista previa", "预览", "पूर्वावलोकन", "Предпросмотр", "معاينة", "Vorschau", "プレビュー", "Prévia", "Pratinjau"),
    "Edit" to proValues("Düzenle", "Modifier", "Editar", "编辑", "संपादित करें", "Изменить", "تعديل", "Bearbeiten", "編集", "Editar", "Ubah"),
    "Delete" to proValues("Sil", "Supprimer", "Eliminar", "删除", "हटाएँ", "Удалить", "حذف", "Löschen", "削除", "Excluir", "Hapus"),
    "Use starter template" to proValues("Başlangıç şablonunu kullan", "Utiliser le modèle de départ", "Usar plantilla inicial", "使用入门模板", "स्टार्टर टेम्पलेट उपयोग करें", "Использовать начальный шаблон", "استخدام القالب المبدئي", "Startvorlage verwenden", "スターターテンプレートを使用", "Usar modelo inicial", "Gunakan templat awal"),
    "Save changes" to proValues("Değişiklikleri kaydet", "Enregistrer les modifications", "Guardar cambios", "保存更改", "बदलाव सहेजें", "Сохранить изменения", "حفظ التغييرات", "Änderungen speichern", "変更を保存", "Salvar alterações", "Simpan perubahan"),
    "Reddit test post" to proValues("Reddit test gönderisi", "Publication de test Reddit", "Publicación de prueba en Reddit", "Reddit 测试帖子", "Reddit टेस्ट पोस्ट", "Пост для теста в Reddit", "منشور اختبار Reddit", "Reddit-Testbeitrag", "Redditテスト投稿", "Post de teste no Reddit", "Posting tes Reddit"),
    "No tester records yet." to proValues("Henüz testçi kaydı yok.", "Aucun testeur enregistré.", "Aún no hay testers guardados.", "尚无测试者记录。", "अभी कोई टेस्टर रिकॉर्ड नहीं है।", "Пока нет записей о тестировщиках.", "لا توجد سجلات مختبرين بعد.", "Noch keine Tester erfasst.", "テスター記録はまだありません。", "Ainda não há testadores registrados.", "Belum ada catatan penguji."),
    "Update tester" to proValues("Testçiyi güncelle", "Mettre à jour le testeur", "Actualizar tester", "更新测试者", "टेस्टर अपडेट करें", "Обновить тестировщика", "تحديث المختبر", "Tester aktualisieren", "テスターを更新", "Atualizar testador", "Perbarui penguji"),
    "Enter your testing links and generate a ready-to-share English post." to proValues("Test bağlantılarını gir ve paylaşmaya hazır İngilizce gönderi oluştur.", "Saisissez vos liens et générez une publication en anglais prête à partager.", "Introduce los enlaces y genera una publicación en inglés lista para compartir.", "输入测试链接并生成可直接分享的英文帖子。", "टेस्ट लिंक दर्ज करें और साझा करने के लिए तैयार अंग्रेज़ी पोस्ट बनाएँ।", "Введите ссылки и создайте готовый пост на английском.", "أدخل روابط الاختبار وأنشئ منشورًا إنجليزيًا جاهزًا للمشاركة.", "Testlinks eingeben und einen fertigen englischen Beitrag erstellen.", "テストリンクを入力し、共有用の英語投稿を作成します。", "Insira os links e gere um post em inglês pronto para compartilhar.", "Masukkan tautan pengujian dan buat posting bahasa Inggris siap dibagikan."),
    "App name" to proValues("Uygulama adı", "Nom de l'application", "Nombre de la app", "应用名称", "ऐप का नाम", "Название приложения", "اسم التطبيق", "App-Name", "アプリ名", "Nome do app", "Nama aplikasi"),
    "Number of testers needed" to proValues("Gerekli testçi sayısı", "Nombre de testeurs nécessaires", "Número de testers necesarios", "所需测试者人数", "आवश्यक टेस्टर संख्या", "Необходимое число тестировщиков", "عدد المختبرين المطلوب", "Benötigte Tester", "必要なテスター数", "Número de testadores necessários", "Jumlah penguji yang diperlukan"),
    "Google Group link" to proValues("Google Group bağlantısı", "Lien Google Group", "Enlace de Google Group", "Google Group 链接", "Google Group लिंक", "Ссылка Google Group", "رابط Google Group", "Google-Group-Link", "Google Groupリンク", "Link do Google Group", "Tautan Google Group"),
    "Opt-in link" to proValues("Teste katılım bağlantısı", "Lien d'inscription au test", "Enlace para unirse a la prueba", "加入测试链接", "टेस्ट में शामिल होने का लिंक", "Ссылка для участия", "رابط الانضمام للاختبار", "Link zur Testteilnahme", "テスト参加リンク", "Link para participar do teste", "Tautan bergabung tes"),
    "Android app link" to proValues("Android uygulama bağlantısı", "Lien de l'application Android", "Enlace de la app Android", "Android 应用链接", "Android ऐप लिंक", "Ссылка на Android-приложение", "رابط تطبيق Android", "Android-App-Link", "Androidアプリリンク", "Link do app Android", "Tautan aplikasi Android"),
    "Saved template" to proValues("Kayıtlı şablon", "Modèle enregistré", "Plantilla guardada", "已保存模板", "सहेजा गया टेम्पलेट", "Сохранённый шаблон", "القالب المحفوظ", "Gespeicherte Vorlage", "保存済みテンプレート", "Modelo salvo", "Templat tersimpan"),
    "Post preview" to proValues("Gönderi önizlemesi", "Aperçu de la publication", "Vista previa de la publicación", "帖子预览", "पोस्ट पूर्वावलोकन", "Предпросмотр публикации", "معاينة المنشور", "Beitragsvorschau", "投稿プレビュー", "Prévia da publicação", "Pratinjau posting"),
    "Share post" to proValues("Gönderiyi paylaş", "Partager la publication", "Compartir publicación", "分享帖子", "पोस्ट साझा करें", "Поделиться публикацией", "مشاركة المنشور", "Beitrag teilen", "投稿を共有", "Compartilhar publicação", "Bagikan posting"),
    "Share test post" to proValues("Test gönderisini paylaş", "Partager la publication de test", "Compartir publicación de prueba", "分享测试帖子", "टेस्ट पोस्ट साझा करें", "Поделиться тестовой публикацией", "مشاركة منشور الاختبار", "Testbeitrag teilen", "テスト投稿を共有", "Compartilhar post de teste", "Bagikan posting tes"),
    "Test guide" to proValues("Test rehberi", "Guide de test", "Guía de prueba", "测试指南", "टेस्ट गाइड", "Руководство", "دليل الاختبار", "Testleitfaden", "テストガイド", "Guia de teste", "Panduan tes"),
    "Community" to proValues("Topluluklar", "Communautés", "Comunidad", "社区", "समुदाय", "Сообщества", "المجتمعات", "Communitys", "コミュニティ", "Comunidade", "Komunitas"),
    "Templates" to proValues("Şablonlar", "Modèles", "Plantillas", "模板", "टेम्पलेट", "Шаблоны", "القوالب", "Vorlagen", "テンプレート", "Modelos", "Templat"),
    "Testers" to proValues("Testçiler", "Testeurs", "Testers", "测试者", "टेस्टर", "Тестировщики", "المختبرون", "Tester", "テスター", "Testadores", "Penguji"),
    "Prepare your usual testing post once; its fields will be filled automatically when you share a new app." to proValues("Sık kullandığın test gönderisini bir kez hazırla; yeni uygulama paylaşırken alanlar otomatik doldurulsun.", "Préparez une fois votre publication; les champs seront remplis automatiquement pour chaque nouvelle application.", "Prepara una vez tu publicación; los campos se completarán automáticamente para cada app.", "只需准备一次常用测试帖子，分享新应用时字段会自动填写。", "अपनी सामान्य टेस्ट पोस्ट एक बार तैयार करें; नया ऐप साझा करते समय फ़ील्ड अपने आप भरेंगे।", "Подготовьте пост один раз; поля будут заполняться автоматически при публикации нового приложения.", "جهّز منشور الاختبار مرة واحدة؛ ستُملأ الحقول تلقائيًا عند مشاركة تطبيق جديد.", "Bereite deinen Testbeitrag einmal vor; die Felder werden beim Teilen einer neuen App automatisch ausgefüllt.", "テスト投稿を一度作成すれば、新しいアプリを共有するときに項目が自動入力されます。", "Prepare sua publicação uma vez; os campos serão preenchidos automaticamente ao compartilhar um novo app.", "Siapkan posting pengujian sekali; kolom akan terisi otomatis saat membagikan aplikasi baru."),
    "1. Name your template" to proValues("1. Şablonuna isim ver", "1. Nommez votre modèle", "1. Nombra tu plantilla", "1. 为模板命名", "1. टेम्पलेट का नाम दें", "1. Назовите шаблон", "1. سمِّ القالب", "1. Vorlage benennen", "1. テンプレート名を入力", "1. Dê um nome ao modelo", "1. Beri nama templat"),
    "2. Write your post" to proValues("2. Gönderi metnini düzenle", "2. Rédigez votre publication", "2. Escribe tu publicación", "2. 编写帖子", "2. पोस्ट लिखें", "2. Напишите публикацию", "2. اكتب المنشور", "2. Beitrag schreiben", "2. 投稿を書く", "2. Escreva a publicação", "2. Tulis posting"),
    "A starter post is already prepared. Edit it to match your own voice." to proValues("Başlangıç metni hazır geldi. İstersen kendi anlatımına göre değiştirebilirsin.", "Un texte de départ est prêt. Modifiez-le selon votre style.", "Ya hay un texto inicial. Edítalo con tu propio estilo.", "已准备好初始帖子，你可以按自己的风格修改。", "शुरुआती पोस्ट तैयार है। इसे अपनी शैली के अनुसार बदलें।", "Начальный текст уже готов. Измените его под свой стиль.", "تم إعداد نص مبدئي. عدّله ليتناسب مع أسلوبك.", "Ein Starttext ist vorbereitet. Passe ihn an deinen Stil an.", "初期文章が用意されています。自分の表現に合わせて編集できます。", "Um texto inicial já está pronto. Edite-o com seu estilo.", "Teks awal sudah disiapkan. Ubah sesuai gaya Anda."),
    "Post text" to proValues("Gönderi metni", "Texte de la publication", "Texto de la publicación", "帖子文本", "पोस्ट टेक्स्ट", "Текст публикации", "نص المنشور", "Beitragstext", "投稿本文", "Texto da publicação", "Teks posting"),
    "3. Add changing information" to proValues("3. Değişecek bilgileri ekle", "3. Ajoutez les informations variables", "3. Añade la información variable", "3. 添加变化的信息", "3. बदलने वाली जानकारी जोड़ें", "3. Добавьте изменяемые данные", "3. أضف المعلومات المتغيرة", "3. Veränderliche Angaben hinzufügen", "3. 変わる情報を追加", "3. Adicione informações variáveis", "3. Tambahkan informasi yang berubah"),
    "Tap a field below. Closed Test Tracker replaces it with the real information when you share the post." to proValues("Aşağıdaki alanlardan birine dokun. Closed Test Tracker, paylaşım sırasında gerçek bilgiyi bu alana yerleştirir.", "Touchez un champ ci-dessous. Closed Test Tracker le remplacera par les informations réelles lors du partage.", "Toca un campo. Closed Test Tracker lo reemplazará con la información real al compartir.", "点击下方字段，分享时 Closed Test Tracker 会将其替换为真实信息。", "नीचे किसी फ़ील्ड पर टैप करें। साझा करते समय Closed Test Tracker उसे वास्तविक जानकारी से बदल देगा।", "Нажмите поле ниже. При публикации Closed Test Tracker заменит его реальными данными.", "اضغط على حقل أدناه. سيستبدله Closed Test Tracker بالمعلومات الحقيقية عند المشاركة.", "Tippe unten auf ein Feld. Closed Test Tracker ersetzt es beim Teilen durch die echten Angaben.", "下の項目をタップすると、共有時に実際の情報へ自動置換されます。", "Toque em um campo. O Closed Test Tracker o substituirá pelas informações reais ao compartilhar.", "Ketuk kolom di bawah. Closed Test Tracker akan menggantinya dengan informasi asli saat dibagikan."),
    "Example preview" to proValues("Örnek önizleme", "Aperçu d'exemple", "Vista previa de ejemplo", "示例预览", "उदाहरण पूर्वावलोकन", "Пример", "معاينة مثال", "Beispielvorschau", "プレビュー例", "Prévia de exemplo", "Contoh pratinjau"),
    "Reset to starter post" to proValues("Başlangıç metnine dön", "Revenir au texte initial", "Restablecer texto inicial", "恢复初始帖子", "शुरुआती पोस्ट पर रीसेट करें", "Вернуть начальный текст", "إعادة النص المبدئي", "Starttext wiederherstellen", "初期文章に戻す", "Restaurar texto inicial", "Kembalikan posting awal"),
    "Template and post details" to proValues("Şablon ve gönderi bilgileri", "Détails du modèle et de la publication", "Detalles de plantilla y publicación", "模板和帖子信息", "टेम्पलेट और पोस्ट विवरण", "Данные шаблона и публикации", "تفاصيل القالب والمنشور", "Vorlagen- und Beitragsdetails", "テンプレートと投稿の詳細", "Detalhes do modelo e da publicação", "Detail templat dan posting"),
    "Fill in the fields. The preview updates immediately; you do not need to work with technical placeholders." to proValues("Boş alanları doldur. Önizleme anında güncellenir; teknik değişkenlerle uğraşman gerekmez.", "Remplissez les champs. L'aperçu se met à jour immédiatement, sans variables techniques.", "Completa los campos. La vista previa se actualiza al instante; no necesitas variables técnicas.", "填写各字段，预览会立即更新，无需处理技术占位符。", "फ़ील्ड भरें। पूर्वावलोकन तुरंत अपडेट होगा; तकनीकी प्लेसहोल्डर की ज़रूरत नहीं।", "Заполните поля. Предпросмотр обновится сразу; технические переменные не нужны.", "املأ الحقول. تتحدث المعاينة فورًا دون الحاجة إلى متغيرات تقنية.", "Fülle die Felder aus. Die Vorschau aktualisiert sich sofort; technische Platzhalter sind nicht nötig.", "空欄を入力するとプレビューがすぐ更新され、技術的な記号を扱う必要はありません。", "Preencha os campos. A prévia atualiza na hora; não é preciso usar variáveis técnicas.", "Isi kolom. Pratinjau langsung diperbarui; tidak perlu placeholder teknis."),
    "e.g. My Test App" to proValues("Örn. Kapalı Test Takibi", "Ex. Mon application de test", "Ej. Mi app de prueba", "例如：我的测试应用", "जैसे मेरा टेस्ट ऐप", "Напр. Моё тестовое приложение", "مثال: تطبيق الاختبار", "z. B. Meine Test-App", "例：テストアプリ", "Ex.: Meu app de teste", "mis. Aplikasi Tes Saya"),
    "Extra message (optional)" to proValues("Ek mesaj (isteğe bağlı)", "Message supplémentaire (facultatif)", "Mensaje adicional (opcional)", "附加消息（可选）", "अतिरिक्त संदेश (वैकल्पिक)", "Дополнительное сообщение (необязательно)", "رسالة إضافية (اختياري)", "Zusätzliche Nachricht (optional)", "追加メッセージ（任意）", "Mensagem extra (opcional)", "Pesan tambahan (opsional)"),
    "Mention any features you especially want testers to try." to proValues("Testçilerden özellikle denemelerini istediğin özellikleri yaz.", "Indiquez les fonctions que les testeurs doivent particulièrement essayer.", "Indica las funciones que quieres que prueben especialmente.", "写下希望测试者重点尝试的功能。", "वे सुविधाएँ लिखें जिन्हें आप विशेष रूप से टेस्ट करवाना चाहते हैं।", "Укажите функции, которые тестировщикам особенно важно проверить.", "اذكر الميزات التي تريد من المختبرين تجربتها بشكل خاص.", "Nenne Funktionen, die Tester besonders ausprobieren sollen.", "特に試してほしい機能を書いてください。", "Mencione recursos que os testadores devem experimentar especialmente.", "Sebutkan fitur yang khusus ingin diuji.")
)

internal fun advancedProCopy(language: AppLanguage, english: String): String? {
    if (language == AppLanguage.EN) return english
    return advancedProStrings[english]?.getOrNull(language.ordinal)
}

internal fun advancedProEnglishKeys(): Set<String> = advancedProStrings.keys
